#!/bin/bash
if [ "$1" != "" ] && [ "$2" != "" ]; then
evup -u $3 $4 $5 $6 $7 $8 $9 $1/$2 $2 > update.sh
else
if [ "$1" != "" ]; then
evup -u ../git/$1 $1 > update.sh
else
echo usage `basename $0` [gitdir] directory
echo evup -u gitdir[../git]/directory directory '>' update.sh
fi
fi
