#!/bin/bash
if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
tar xvf $1/$4$3-$2.tar.bz2
else
if [ "$1" != "" ] && [ "$2" != "" ]; then
tar xvf ../tar/$2-$1.tar.bz2
else
echo usage `basename $0` [tardir] hostname directory [prefix]
echo tar xvf tardir[../tar]/[prefix]directory-hostname.tar.bz2
fi
fi
