#!/bin/bash
if [ "$1" != "" ] && [ "$2" != "" ] && [ "$3" != "" ]; then
evup -u $4 $5 $6 $1/$2/$3 $3 > update.sh
else
if [ "$1" != "" ] && [ "$2" != "" ]; then
evup -u ../tar/$1/$2 $2 > update.sh
else
echo usage `basename $0` [tardir] host directory
echo evup -u tardir[../tar]/host/directory directory '>' update.sh
fi
fi
